[package]
name = "hello"
version = "0.1.0"
edition = "2021"

[dependencies]
once_cell = "1.18.0"
parking_lot = "0.12.1"
dashmap = "5.5.3"
log = "0.4.20"
num-traits = "0.2.17"
thread_local = "1.1.7"
bytesize = "1.3.0"
regex = "1.11.1"
